# POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_MODE='awesome-fontconfig'

# ICONS
POWERLEVEL9K_HOME_ICON=''
POWERLEVEL9K_HOME_SUB_ICON=''
POWERLEVEL9K_FOLDER_ICON=''
POWERLEVEL9K_HOST_ICON=""
POWERLEVEL9K_SSH_ICON=""
POWERLEVEL9K_USER_ICON=""
POWERLEVEL9K_ROOT_ICON=""
POWERLEVEL9K_TIME_ICON=''
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=''
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
POWERLEVEL9K_BACKGROUND_JOBS_ICON='⚑'
POWERLEVEL9K_DOT_ICON='⍟'

# VCS ICONS
POWERLEVEL9K_VCS_GIT_ICON=''
POWERLEVEL9K_VCS_BRANCH_ICON=''
POWERLEVEL9K_VCS_STAGED_ICON=''
POWERLEVEL9K_VCS_UNTRACKED_ICON=''
POWERLEVEL9K_VCS_UNSTAGED_ICON=''
POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON=''
POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON=''

# Colors
POWERLEVEL9K_DEFAULT_BACKGROUND='09'
POWERLEVEL9K_DEFAULT_FOREGROUND='black'

# STATUS COLORS
POWERLEVEL9K_STATUS_OK_BACKGROUND="09"
POWERLEVEL9K_STATUS_OK_FOREGROUND="green"
POWERLEVEL9K_STATUS_ERROR_BACKGROUND="230"
POWERLEVEL9K_STATUS_ERROR_FOREGROUND="09"

# DIR COLORS
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='09'
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='black'
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="green"

# VCS COLORS
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='black'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='119'
# POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='black'
# POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='214'
# POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='196'
# POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='yellow'

# VIM COLORS
POWERLEVEL9K_VI_MODE_INSERT_BACKGROUND='005'
POWERLEVEL9K_VI_MODE_INSERT_FOREGROUND='236'
POWERLEVEL9K_VI_MODE_NORMAL_BACKGROUND='245'
POWERLEVEL9K_VI_MODE_NORMAL_FOREGROUND='236'

# RAM COLORS
POWERLEVEL9K_RAM_BACKGROUND="09"
POWERLEVEL9K_RAM_FOREGROUND="black"
POWERLEVEL9K_RAM_VISUAL_IDENTIFIER="blue"

# CPU COLORS
POWERLEVEL9K_LOAD_CRITICAL_FOREGROUND="black"
POWERLEVEL9K_LOAD_CRITICAL_BACKGROUND="yellow"
POWERLEVEL9K_LOAD_CRITICAL_VISUAL_IDENTIFIER_COLOR="red"
POWERLEVEL9K_LOAD_WARNING_FOREGROUND="black"
POWERLEVEL9K_LOAD_WARNING_BACKGROUND="230"
POWERLEVEL9K_LOAD_WARNING_VISUAL_IDENTIFIER_COLOR="yellow"
POWERLEVEL9K_LOAD_NORMAL_FOREGROUND="black"
POWERLEVEL9K_LOAD_NORMAL_BACKGROUND="119"
POWERLEVEL9K_LOAD_NORMAL_VISUAL_IDENTIFIER_COLOR="blue"

# CONFIGS
POWERLEVEL9K_STATUS_VERBOSE=false

POWERLEVEL9K_SHORTEN_DIR_LENGTH=4
POWERLEVEL9K_SHORTEN_DELIMITER=""
# POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_left"
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_middle"

POWERLEVEL9K_HOME_FOLDER_ABBREVIATION=""
POWERLEVEL9K_HOME_SUB_FOLDER_ABBREVIATION=""
POWERLEVEL9K_DIR_SHOW_WRITABLE=true
POWERLEVEL9K_SHOW_CHANGESET=true
POWERLEVEL9K_CHANGESET_HASH_LENGTH=6

POWERLEVEL9K_RAM_ELEMENTS=(ram_free)

# FORMATTERS
POWERLEVEL9K_CONTEXT_TEMPLATE="%K{09}%F{119}⎮ $(print_icon 'USER_ICON') %F{230}%n"
POWERLEVEL9K_DIR_PATH_SEPARATOR="%K{09}%F{yellow} $(print_icon 'LEFT_SUBSEGMENT_SEPARATOR')%K{09}%F{230} "
POWERLEVEL9K_TIME_FORMAT="%D{%H:%M  %d.%m.%y}"
